name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: --health-cmd "mongosh --eval 'db.runCommand(\"ping\").ok'" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unrar

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Lint Python code
      run: |
        pip install flake8
        flake8 backend/ --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run backend smoke test
      run: |
        python -c "import flask; import comicinfo; import mangaupdates" || exit 1

    - name: Build Docker image
      run: docker build -t manga-release-date-fixer .

    - name: Docker run (smoke test)
      run: |
        docker run --rm -d --name manga-fixer-test -p 1996:1996 -v "$PWD/test_comics:/comics" manga-release-date-fixer
        sleep 10
        curl --fail http://localhost:1996/api/chapters
        docker stop manga-fixer-test

    - name: Upload frontend artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend
        path: frontend/